// src/app/results/results.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-results',
  templateUrl: './results.component.html',
  styleUrls: ['./results.component.css']
})
export class ResultsComponent{
  @Input() options: any[] = [];

  totalVotes() {
    return this.options.reduce( (total, { votes }) => total + votes, 0);
  }
  calcPercent(option: any){
    if (!option.votes) return 0;
    return (option.votes/this.totalVotes()) * 100;
  }
  
}

<ul>
    <li *ngFor="let option of options; index as index">{{option.name}} - {{calcPercent(option).toFixed(2)}}% ({{option.votes}})</li>
</ul>

// src/components/Results.vue
<template>
    <ul>
        <li v-for="option in options" :key="option.name">{{option.name}} - {{option.votes}} votos ({{percentage(options,option)}}%)</li>
    </ul>
</template>

<script>
export default {
    name: 'Results',
    props: {
        options: Array,
    },
    methods: {
        percentage(options,option){
            let total = options.reduce( ( sum, { votes } ) => sum + votes , 0)
            return ((option.votes/total)*100).toFixed(2)
        }
    },
    
}
</script>

<style>
li{
    text-align: left;
}
</style>
